spring:
  main:
    banner-mode: "off"
server:
  port : 28080


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.golan: TRACE
    org.springframework.web: TRACE
    org.hibernate: ERROR
